import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const playfair = localFont({
  src: "./fonts/PlayfairVariable.ttf",
  variable: "--font-playfair",
  weight: "100 900",
})

const openSans = localFont({
  src: "./fonts/OpenSansVariable.ttf",
  variable: "--font-open-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${openSans.className} ${playfair.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
